// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureX.Api.Data;

#nullable disable

namespace SecureX.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919030000_EnforceActivePayoutUniqueness")]
    partial class EnforceActivePayoutUniqueness : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureX.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionDetails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_details");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text")
                        .HasColumnName("previous_status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("TriggerActor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_actor");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SecureX.Api.Models.PayoutNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerMerchantReference")
                        .HasColumnType("text")
                        .HasColumnName("customer_merchant_reference");

                    b.Property<bool>("Duplicate")
                        .HasColumnType("boolean");

                    b.Property<string>("EventKey")
                        .HasColumnType("text")
                        .HasColumnName("event_key");

                    b.Property<bool>("HashValid")
                        .HasColumnType("boolean")
                        .HasColumnName("hash_valid");

                    b.Property<string>("MerchantReference")
                        .HasColumnType("text")
                        .HasColumnName("merchant_reference");

                    b.Property<string>("PayoutId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payout_id");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("SiteCode")
                        .HasColumnType("text")
                        .HasColumnName("site_code");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("SubStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PayoutId")
                        .HasDatabaseName("idx_payout_notifications_payout_id");

                    b.ToTable("payout_notifications", (string)null);
                });

            modelBuilder.Entity("SecureX.Api.Models.PendingPayout", b =>
                {
                    b.Property<string>("PayoutId")
                        .HasColumnType("text")
                        .HasColumnName("payout_id");

                    b.Property<string>("DealReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deal_reference");

                    b.Property<int>("PollCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("PayoutId");

                    b.HasIndex("Resolved")
                        .HasDatabaseName("idx_pending_payouts_resolved");

                    b.HasIndex("DealReference")
                        .HasDatabaseName("ux_pending_payouts_active_deal_reference")
                        .HasFilter("resolved = false")
                        .IsUnique();

                    b.ToTable("pending_payouts", (string)null);
                });

            modelBuilder.Entity("SecureX.Api.Models.ReconciliationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlertFired")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_fired");

                    b.Property<decimal>("Discrepancy")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("discrepancy");

                    b.Property<decimal>("ExpectedFloat")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("expected_float");

                    b.Property<decimal?>("OzowFloat")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("ozow_float");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.HasKey("Id");

                    b.ToTable("reconciliation_reports", (string)null);
                });

            modelBuilder.Entity("SecureX.Api.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BuyerFee")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("buyer_fee");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DealReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deal_reference");

                    b.Property<DateTime?>("InspectionWindowEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inspection_window_ends_at");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_description");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_title");

                    b.Property<decimal>("ItemValue")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("item_value");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("platform_fee");

                    b.Property<decimal>("SellerFee")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("seller_fee");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("SellerLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seller_location");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCheckoutAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_checkout_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("DealReference")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SecureX.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AmlStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankBranchCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_branch_code");

                    b.Property<string>("BankGroupId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_group_id");

                    b.Property<string>("BankVerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_verification_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("IdCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_number");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("LivenessStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("liveness_status");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmileIdAmlJobId")
                        .HasColumnType("text")
                        .HasColumnName("smile_id_aml_job_id");

                    b.Property<string>("SmileIdJobId")
                        .HasColumnType("text")
                        .HasColumnName("smile_id_job_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SecureX.Api.Models.WebhookEvent", b =>
                {
                    b.Property<string>("EventKey")
                        .HasColumnType("text")
                        .HasColumnName("event_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PayoutId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payout_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubStatus")
                        .HasColumnType("integer");

                    b.HasKey("EventKey");

                    b.ToTable("webhook_events", (string)null);
                });

            modelBuilder.Entity("SecureX.Api.Models.AuditLog", b =>
                {
                    b.HasOne("SecureX.Api.Models.Transaction", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("TransactionId");
                });

            modelBuilder.Entity("SecureX.Api.Models.Transaction", b =>
                {
                    b.HasOne("SecureX.Api.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SecureX.Api.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SecureX.Api.Models.Transaction", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
