using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SecureX.Api.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                -- Existing JS backend tables: create only if missing
                CREATE TABLE IF NOT EXISTS payout_notifications (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    event_key text,
                    payout_id text NOT NULL,
                    site_code text,
                    merchant_reference text,
                    customer_merchant_reference text,
                    ""Status"" integer,
                    ""SubStatus"" integer,
                    hash_valid boolean NOT NULL DEFAULT false,
                    ""Duplicate"" boolean NOT NULL DEFAULT false,
                    ""Reason"" text,
                    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
                    created_at timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_payout_notifications"" PRIMARY KEY (""Id"")
                );
                CREATE INDEX IF NOT EXISTS idx_payout_notifications_payout_id
                    ON payout_notifications (payout_id);

                CREATE TABLE IF NOT EXISTS webhook_events (
                    event_key text NOT NULL,
                    payout_id text NOT NULL,
                    ""Status"" integer NOT NULL DEFAULT 0,
                    ""SubStatus"" integer NOT NULL DEFAULT 0,
                    created_at timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_webhook_events"" PRIMARY KEY (event_key)
                );

                -- New tables
                CREATE TABLE IF NOT EXISTS reconciliation_reports (
                    ""Id"" uuid NOT NULL,
                    run_at timestamptz NOT NULL,
                    expected_float numeric(14,2) NOT NULL,
                    ozow_float numeric(14,2) NOT NULL,
                    discrepancy numeric(14,2) NOT NULL,
                    alert_fired boolean NOT NULL,
                    CONSTRAINT ""PK_reconciliation_reports"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS users (
                    ""Id"" uuid NOT NULL,
                    id_number text NOT NULL DEFAULT '',
                    bank_account_number text NOT NULL DEFAULT '',
                    bank_branch_code text NOT NULL DEFAULT '',
                    ""Email"" text NOT NULL DEFAULT '',
                    ""Phone"" text NOT NULL DEFAULT '',
                    smile_verification_status text NOT NULL DEFAULT 'Pending',
                    bank_verification_status text NOT NULL DEFAULT 'Pending',
                    created_at timestamptz NOT NULL DEFAULT now(),
                    updated_at timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_users"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS transactions (
                    ""Id"" uuid NOT NULL,
                    deal_reference text NOT NULL,
                    buyer_id uuid NOT NULL,
                    seller_id uuid NOT NULL,
                    item_value numeric(12,2) NOT NULL,
                    platform_fee numeric(12,2) NOT NULL,
                    total_checkout_amount numeric(12,2) NOT NULL,
                    service_type text NOT NULL,
                    status text NOT NULL,
                    version integer NOT NULL DEFAULT 1,
                    created_at timestamptz NOT NULL DEFAULT now(),
                    updated_at timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_transactions"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_transactions_users_buyer_id""
                        FOREIGN KEY (buyer_id) REFERENCES users(""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_transactions_users_seller_id""
                        FOREIGN KEY (seller_id) REFERENCES users(""Id"") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_transactions_deal_reference""
                    ON transactions (deal_reference);
                CREATE INDEX IF NOT EXISTS ""IX_transactions_buyer_id""
                    ON transactions (buyer_id);
                CREATE INDEX IF NOT EXISTS ""IX_transactions_seller_id""
                    ON transactions (seller_id);

                CREATE TABLE IF NOT EXISTS audit_logs (
                    ""Id"" uuid NOT NULL,
                    transaction_id uuid NOT NULL,
                    previous_status text,
                    new_status text NOT NULL,
                    trigger_actor text NOT NULL DEFAULT '',
                    action_details text NOT NULL DEFAULT '',
                    timestamp timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_audit_logs"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_audit_logs_transactions_transaction_id""
                        FOREIGN KEY (transaction_id) REFERENCES transactions(""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_audit_logs_transaction_id""
                    ON audit_logs (transaction_id);

                CREATE SEQUENCE IF NOT EXISTS deal_reference_seq START 1 INCREMENT 1;
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS audit_logs;
                DROP TABLE IF EXISTS transactions;
                DROP TABLE IF EXISTS users;
                DROP TABLE IF EXISTS reconciliation_reports;
                DROP TABLE IF EXISTS webhook_events;
                DROP TABLE IF EXISTS payout_notifications;
                DROP SEQUENCE IF EXISTS deal_reference_seq;
            ");
        }
    }
}
